=== faizanshaikh0303/Company-Ownership-Database-Management-System/XQuery/schema.xsd
<!--I pledge my honor that all parts of this project were done by me alone and without collaboration with anybody else.

CSE Project 3
Name: Shubham Kumar Jain
SBU ID: 111482623
Brief Description: The schema.xsd file validates the data from the xml file-->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:complexType name="entityType">
    <xs:sequence>
        <xs:element name="id" type="xs:string"/>
        <xs:element name="name" type="xs:string"/>
        <xs:element name="owns">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="own" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="cid" type="xs:string"/>
                            <xs:element name= "shares" type="xs:integer"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
        </xs:element>
    </xs:sequence>
</xs:complexType>  


<xs:complexType name="personType">
    <xs:sequence>
            <xs:element name="entity" type="entityType"/>
    </xs:sequence>
</xs:complexType> 


<xs:complexType name="companyType">
    <xs:sequence>
        <xs:element name="entity" type="entityType"/>
        <xs:element name ="shares" type="xs:positiveInteger"/>
        <xs:element name = "shareprice" type="xs:decimal"/>
        <xs:element name= "board">
            <xs:complexType>
                <xs:sequence>
                    <xs:element name="member" minOccurs="0" maxOccurs="unbounded">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name="pid" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                </xs:sequence>
            </xs:complexType>
        </xs:element>
        <xs:element name="industries">
            <xs:complexType>
                <xs:sequence>
                    <xs:element name="industry" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
                </xs:sequence>
            </xs:complexType>
        </xs:element>
    </xs:sequence>
</xs:complexType>


<xs:element name="entities">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="company" type="companyType" minOccurs="0" maxOccurs="unbounded" />
            <xs:element name="person" type="personType" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
    <xs:key name="entityid2">
        <xs:selector xpath="person/entity" />
        <xs:field xpath="id" />
    </xs:key>
    <xs:key name="entityid1">
        <xs:selector xpath="company/entity" />
        <xs:field xpath="id" />
    </xs:key>
    <xs:keyref name="companyownscompanyid" refer="entityid1">
        <xs:selector xpath="company/entity/owns/own" />
        <xs:field xpath="cid" />
    </xs:keyref>
    <xs:keyref name="personinboard" refer="entityid2">
        <xs:selector xpath="company/board/member" />
        <xs:field xpath="pid" />
    </xs:keyref>
    <xs:keyref name="personownscompanyid" refer="entityid1">
        <xs:selector xpath="person/entity/owns/own" />
        <xs:field xpath="cid" />
    </xs:keyref>
</xs:element>

</xs:schema>

=== faizanshaikh0303/Company-Ownership-Database-Management-System/XQuery/database.xml
<!--I pledge my honor that all parts of this project were done by me alone and without collaboration with anybody else.

CSE Project 3
Name: Shubham Kumar Jain
SBU ID: 111482623
Brief Description: The database.xml file describes the data of the woco database-->

<entities xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema.xsd">

<company>
    <entity>
        <id>c1</id>
        <name>QUE</name>
        <owns>
            <own>
                <cid>c2</cid>
                <shares>10000</shares>
            </own>
            <own>
                <cid>c4</cid>
                <shares>20000</shares>
            </own>
            <own>
                <cid>c8</cid>
                <shares>30000</shares>
            </own>
        </owns>
    </entity>
    <shares>150000</shares>
    <shareprice>30</shareprice>
    <board>
        <member><pid>p3</pid></member>
        <member><pid>p1</pid></member>
        <member><pid>p4</pid></member>
    </board>
    <industries>
        <industry>Software</industry>
        <industry>Accounting</industry>
    </industries>
</company>

<company>
    <entity>
        <id>c2</id>
        <name>RHC</name>
        <owns>
        </owns>
    </entity>
    <shares>250000</shares>
    <shareprice>20</shareprice>
    <board>
        <member><pid>p1</pid></member>
        <member><pid>p2</pid></member>
        <member><pid>p5</pid></member>
    </board>
    <industries>
        <industry>Accounting</industry>
    </industries>
</company>

<company>
    <entity>
        <id>c3</id>
        <name>Alf</name>
        <owns>
            <own>
                <cid>c9</cid>
                <shares>-100000</shares>
            </own>
            <own>
                <cid>c4</cid>
                <shares>400000</shares>
            </own>
            <own>
                <cid>c8</cid>
                <shares>100000</shares>
            </own>
        </owns>
    </entity>
    <shares>10000000</shares>
    <shareprice>700</shareprice>
    <board>
        <member><pid>p6</pid></member>
        <member><pid>p7</pid></member>
        <member><pid>p1</pid></member>
    </board>
    <industries>
        <industry>Software</industry>
        <industry>Automotive</industry>
    </industries>
</company>

<company>
    <entity>
        <id>c4</id>
        <name>Elgog</name>
        <owns>
            <own>
                <cid>c6</cid>
                <shares>5000</shares>
            </own>
        </owns>
    </entity>
    <shares>1000000</shares>
    <shareprice>400</shareprice>
    <board>
        <member><pid>p6</pid></member>
        <member><pid>p7</pid></member>
        <member><pid>p5</pid></member>
    </board>
    <industries>
        <industry>Software</industry>
        <industry>Search</industry>
    </industries>
</company>

<company>
    <entity>
        <id>c5</id>
        <name>Tfos</name>
        <owns>
            <own>
                <cid>c6</cid>
                <shares>30000</shares>
            </own>
            <own>
                <cid>c7</cid>
                <shares>50000</shares>
            </own>
            <own>
                <cid>c1</cid>
                <shares>200000</shares>
            </own>
        </owns>
    </entity>
    <shares>10000000</shares>
    <shareprice>300</shareprice>
    <board>
        <member><pid>p2</pid></member>
        <member><pid>p5</pid></member>
        <member><pid>p4</pid></member>
    </board>
    <industries>
        <industry>Software</industry>
        <industry>Hardware</industry>
    </industries>
</company>

<company>
    <entity>
        <id>c6</id>
        <name>Ohay</name>
        <owns>
        </owns>
    </entity>
    <shares>180000</shares>
    <shareprice>50</shareprice>
    <board>
        <member><pid>p2</pid></member>
        <member><pid>p4</pid></member>
        <member><pid>p8</pid></member>
    </board>
    <industries>
        <industry>Search</industry>
    </industries>
</company>

<company>
    <entity>
        <id>c7</id>
        <name>Gnow</name>
        <owns>
        </owns>
    </entity>
    <shares>150000</shares>
    <shareprice>300</shareprice>
    <board>
        <member><pid>p2</pid></member>
        <member><pid>p3</pid></member>
        <member><pid>p4</pid></member>
    </board>
    <industries>
        <industry>Search</industry>
    </industries>
</company>

<company>
    <entity>
        <id>c8</id>
        <name>Elpa</name>
        <owns>
            <own>
                <cid>c5</cid>
                <shares>20000</shares>
            </own>
            <own>
                <cid>c4</cid>
                <shares>30000</shares>
            </own>
        </owns>
    </entity>
    <shares>9000000</shares>
    <shareprice>300</shareprice>
    <board>
        <member><pid>p2</pid></member>
        <member><pid>p3</pid></member>
        <member><pid>p8</pid></member>
    </board>
    <industries>
        <industry>Software</industry>
        <industry>Hardware</industry>
    </industries>
</company>

<company>
    <entity>
        <id>c9</id>
        <name>Ydex</name>
        <owns>
        </owns>
    </entity>
    <shares>5000000</shares>
    <shareprice>100</shareprice>
    <board>
        <member><pid>p6</pid></member>
        <member><pid>p3</pid></member>
        <member><pid>p8</pid></member>
    </board>
    <industries>
        <industry>Software</industry>
        <industry>Search</industry>
    </industries>
</company>

<person>
    <entity>
        <id>p1</id>
        <name>Bill Doe</name>
        <owns>
            <own>
                <cid>c5</cid>
                <shares>30000</shares>
            </own>
            <own>
                <cid>c8</cid>
                <shares>100000</shares>
            </own>
        </owns>
    </entity>
</person>

<person>
    <entity>
        <id>p2</id>
        <name>Bill Seth</name>
        <owns>
            <own>
                <cid>c7</cid>
                <shares>40000</shares>
            </own>
            <own>
                <cid>c4</cid>
                <shares>20000</shares>
            </own>
        </owns>
    </entity>
</person>

<person>
    <entity>
        <id>p3</id>
        <name>John Smyth</name>
        <owns>
            <own>
                <cid>c1</cid>
                <shares>20000</shares>
            </own>
            <own>
                <cid>c2</cid>
                <shares>20000</shares>
            </own>
            <own>
                <cid>c5</cid>
                <shares>800000</shares>
            </own>
        </owns>
    </entity>
</person>

<person>
    <entity>
        <id>p4</id>
        <name>Anne Smyle</name>
        <owns>
            <own>
                <cid>c2</cid>
                <shares>30000</shares>
            </own>
            <own>
                <cid>c5</cid>
                <shares>40000</shares>
            </own>
            <own>
                <cid>c3</cid>
                <shares>500000</shares>
            </own>
        </owns>
    </entity>
</person>

<person>
    <entity>
        <id>p5</id>
        <name>Steve Lamp</name>
        <owns>
            <own>
                <cid>c8</cid>
                <shares>90000</shares>
            </own>
            <own>
                <cid>c1</cid>
                <shares>50000</shares>
            </own>
            <own>
                <cid>c6</cid>
                <shares>50000</shares>
            </own>
            <own>
                <cid>c2</cid>
                <shares>70000</shares>
            </own>
        </owns>
    </entity>
</person>

<person>
    <entity>
        <id>p6</id>
        <name>May Serge</name>
        <owns>
            <own>
                <cid>c8</cid>
                <shares>-10000</shares>
            </own>
            <own>
                <cid>c9</cid>
                <shares>-40000</shares>
            </own>
            <own>
                <cid>c3</cid>
                <shares>500000</shares>
            </own>
            <own>
                <cid>c2</cid>
                <shares>40000</shares>
            </own>
        </owns>
    </entity>
</person>

<person>
    <entity>
        <id>p7</id>
        <name>Bill Public</name>
        <owns>
            <own>
                <cid>c7</cid>
                <shares>80000</shares>
            </own>
            <own>
                <cid>c4</cid>
                <shares>30000</shares>
            </own>
            <own>
                <cid>c1</cid>
                <shares>30000</shares>
            </own>
            <own>
                <cid>c5</cid>
                <shares>300000</shares>
            </own>
            <own>
                <cid>c2</cid>
                <shares>-9000</shares>
            </own>
        </owns>
    </entity>
</person>

<person>
    <entity>
        <id>p8</id>
        <name>Muck Lain</name>
        <owns>
            <own>
                <cid>c2</cid>
                <shares>60000</shares>
            </own>
            <own>
                <cid>c6</cid>
                <shares>-40000</shares>
            </own>
            <own>
                <cid>c9</cid>
                <shares>-80000</shares>
            </own>
            <own>
                <cid>c8</cid>
                <shares>30000</shares>
            </own>
        </owns>
    </entity>
</person>

</entities>
